### ISSUE TITLE
Add option to shrinkwrap devDependencies

### ISSUE THREAD

**Issue by felixfbecker** [greenkeeperio/greenkeeper-shrinkwrap#11]
We shrinkwrap our devDependencies because we had a lot of build failures due to in-version breaking changes or bugs in build tools. To include them, you need to run `npm shrinkwrap --dev`

**Comment by boennemann** [comment]
Hey @felixfbecker,
thanks for the feedback. `--dev` is the default with npm@4. 
Could you try updating npm, while we further investigate?

Best,
Stephan

**Comment by boennemann** [comment]
Yay, open source. Didn't even see there was a PR that fixes this already.
Should work now.

https://github.com/greenkeeperio/greenkeeper-shrinkwrap/pull/13
