### ISSUE TITLE
Bug: shrinkwrap commit fails on dev dependency update

### ISSUE THREAD

**Issue by sanderploegsma** [greenkeeperio/greenkeeper-shrinkwrap#12]
We are being flooded with breaking greenkeeper branches, because whenever a dev dependency is updated, this script tries to commit without changes, because the shrinkwrap file does not need an update. 

It should either skip dev dependency updates, or check if there are changes to be committed before trying to commit anything.

**Comment by boennemann** [comment]
Hey @sanderploegsma,

thanks for the bug report – this is a problem.
With npm@4 devDependencies are shrinkwrapped, too, which would fix this problem.
Could you try updating npm, while we further investigate?

Best,
Stephan

**Comment by boennemann** [comment]
Yay, open source. Didn't even see there was a PR that fixes this already.
Should work now.

https://github.com/greenkeeperio/greenkeeper-shrinkwrap/pull/13
