### ISSUE TITLE
publish in npm

### ISSUE THREAD

**Issue by php-workx** [greenkeeperio/greenkeeper-shrinkwrap#3]
Hey guys, 

would you mind to publish the latest version on npm registry also? At the moment the setup is not working like expected:

```
$ npm install -g greenkeeper-shrinkwrap

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/greenkeeper-shrinkwrap
npm ERR! 404 
npm ERR! 404  'greenkeeper-shrinkwrap' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

Thanks!

**Comment by SpainTrain** [comment]
In the description it says `WIP, not working yet.`

**Comment by boennemann** [comment]
Hey @php-workx and @SpainTrain,

Good news: I finally got around to make this work and it's published on npm
Bad news: It only works on Travis CI for now #5 

Best,
Stephan
